apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightspeed-regression-testing
  labels:
    app: lightspeed-regression-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lightspeed-regression-testing
  template:
    metadata:
      labels:
        app: lightspeed-regression-testing
        service: lightspeed-core
        mcp-service: test-mcp-server
    spec:
      volumes:
        - name: lightspeed-stack-config
          configMap:
            name: lightspeed-stack-config
        - name: lightspeed-profile
          configMap:
            name: lightspeed-profile
        - name: llama-stack-config
          configMap:
            name: llama-stack-config
        - name: feedback-data
          persistentVolumeClaim:
            claimName: feedback-data
        - name: rag-content
          emptyDir: {}

      initContainers:
        - name: rag-content-init
          image: quay.io/redhat-ai-dev/rag-content:release-1.9-lls-0.4.3-d0444cd9b57222ec9bdbaa36354337480a2ecf97
          command:
            - /bin/sh
            - -c
            - |
              cp -r /rag/embeddings_model /rag-content/
              cp -r /rag/vector_db /rag-content/
          volumeMounts:
            - mountPath: /rag-content
              name: rag-content

      containers:
        - name: lightspeed-core
          image: quay.io/lightspeed-core/lightspeed-stack:dev-latest
          resources:
            requests:
              cpu: "750m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /readiness
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          volumeMounts:
            - name: lightspeed-stack-config
              mountPath: /app-root/lightspeed-stack.yaml
              subPath: lightspeed-stack.yaml
            - name: lightspeed-profile
              mountPath: /app-root/rhdh-profile.py
              subPath: rhdh-profile.py
            - name: llama-stack-config
              mountPath: /app-root/config.yaml
              subPath: config.yaml
            - name: feedback-data
              mountPath: /tmp/data/feedback
              subPath: feedback
            - name: rag-content
              mountPath: /rag-content
            - name: feedback-data
              mountPath: /tmp/results
              subPath: results
          envFrom:
            - secretRef:
                name: llama-stack-secrets
          env:
            - name: ENABLE_VALIDATION
              value: "true"
            - name: VALIDATION_PROVIDER
              value: "vllm"
            - name: VALIDATION_MODEL_NAME
              value: "redhataillama-31-8b-instruct"

        - name: test-mcp-server
          image: quay.io/redhat-ai-dev/test-mcp-server:latest
          env:
            - name: MCP_SERVER_PORT
              value: '8888'
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"